trigger:
- sprint_1_release

pool:
  name: Az

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd _StudentCoursesRestAPI/K8s/
      kubectl apply -f mysql-aws.yml
      kubectl apply -f flask-aws.yml
      sleep 10s
      kubectl get svc
