# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- sprint_1_release

pool:
  name: Az-Pool

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker build -t us-central1-docker.pkg.dev/crypto-talon-365110/tsar7/src:latest .'
  displayName: build

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker push us-central1-docker.pkg.dev/crypto-talon-365110/tsar7/src:latest
  displayName: push