# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Az

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'caesar269 / src'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f '$(System.System.DefaultWorkingDirectory)/**/*mysql-aws.yml'
      kubectl apply -f '$(System.System.DefaultWorkingDirectory)/**/*flask-aws.yml'
      sleep 10s
      kubectl get svc