trigger:
- sprint_1_release

pool:
  name: Az

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f ./K8s/mysql-aws.yml
      kubectl apply -f ./K8s/flask-aws.yml
      sleep 10s
      kubectl get svc