trigger:
- sprint_1_release

pool:
  name: Az-Pool

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker build -t us-central1-docker.pkg.dev/crypto-talon-365110/tsar7/src:latest .'
  displayName: build
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker push us-central1-docker.pkg.dev/crypto-talon-365110/tsar7/src:latest
  displayName: push
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f ./K8s/mysql-aws.yml
      kubectl apply -f ./K8s/flask-aws.yml
      sleep 10s
      kubectl get svc
  displayName: deploy